import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, serviceRoleKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const errors: string[] = [];
  const upsert = async (table: string, data: any[], onConflict?: string) => {
    const opts = onConflict ? { onConflict } : {};
    const { data: result, error, status, statusText } = await supabase.from(table).upsert(data, opts).select();
    if (error) errors.push(`${table}: ${error.message} (${error.code}) status=${status}`);
    else errors.push(`${table}: OK inserted=${result?.length ?? 0} status=${status}`);
  };

  try {
    // 1. Create organization
    await upsert("organizations", [
      { id: "org-eskilstuna", name: "Eskilstuna Municipality", population: 107000, region: "Södermanland", type: "municipality" },
      { id: "org-region-sormland", name: "Region Sörmland", population: 300000, region: "Södermanland", type: "region" },
    ]);

    // 2. Create demo users
    const users = [
      { email: "elena@eskilstuna.demo", password: "demo1234", display_name: "Elena Vasquez", title: "Chief Technology Officer", persona: "elena", role: "cto" as const },
      { email: "lars@eskilstuna.demo", password: "demo1234", display_name: "Lars Eriksson", title: "Chief Financial Officer", persona: "lars", role: "cfo" as const },
      { email: "arthur@eskilstuna.demo", password: "demo1234", display_name: "Arthur Lindberg", title: "Chief Operating Officer", persona: "arthur", role: "coo" as const },
    ];

    for (const u of users) {
      const { data: existingUsers } = await supabase.auth.admin.listUsers();
      const existing = existingUsers?.users?.find((eu: any) => eu.email === u.email);

      let userId: string;
      if (existing) {
        userId = existing.id;
      } else {
        const { data, error } = await supabase.auth.admin.createUser({
          email: u.email,
          password: u.password,
          email_confirm: true,
          user_metadata: { display_name: u.display_name },
        });
        if (error) throw error;
        userId = data.user.id;
      }

      await supabase.from("profiles").upsert({
        user_id: userId,
        display_name: u.display_name,
        email: u.email,
        title: u.title,
        org_id: "org-eskilstuna",
        persona: u.persona,
      }, { onConflict: "user_id" });

      await supabase.from("user_roles").upsert({
        user_id: userId,
        role: u.role,
      }, { onConflict: "user_id,role" });
    }

    // 3. Seed vendors
    await upsert("vendors", [
      { id: "VND-001", name: "Microsoft", country: "USA", contact_email: "enterprise@microsoft.com", website: "https://microsoft.com", org_id: "org-eskilstuna" },
      { id: "VND-002", name: "CGI", country: "Canada", contact_email: "nordic@cgi.com", website: "https://cgi.com", org_id: "org-eskilstuna" },
      { id: "VND-003", name: "Visma", country: "Norway", contact_email: "support@visma.com", website: "https://visma.com", org_id: "org-eskilstuna" },
      { id: "VND-004", name: "Dell / Cisco", country: "USA", contact_email: "enterprise@dell.com", website: "https://dell.com", org_id: "org-eskilstuna" },
      { id: "VND-005", name: "Open ePlatform", country: "Sweden", contact_email: "info@oeplatform.org", website: "https://oeplatform.org", org_id: "org-eskilstuna" },
      { id: "VND-006", name: "Esri / Lantmäteriet", country: "Sweden", contact_email: "info@esri.se", website: "https://esri.com", org_id: "org-eskilstuna" },
      { id: "VND-007", name: "IST", country: "Sweden", contact_email: "support@ist.com", website: "https://ist.com", org_id: "org-eskilstuna" },
      { id: "VND-008", name: "Tekis", country: "Sweden", contact_email: "info@tekis.se", website: "https://tekis.se", org_id: "org-eskilstuna" },
      { id: "VND-009", name: "Dell EMC", country: "USA", contact_email: "storage@dell.com", website: "https://dell.com", org_id: "org-eskilstuna" },
      { id: "VND-010", name: "Formpipe", country: "Sweden", contact_email: "sales@formpipe.com", website: "https://formpipe.com", org_id: "org-eskilstuna" },
      { id: "VND-011", name: "Rasa Technologies", country: "Germany", contact_email: "sales@rasa.com", website: "https://rasa.com", org_id: "org-eskilstuna" },
    ]);

    // 4. Seed systems (with internet_facing)
    await upsert("systems", [
      { id: "SYS-001", name: "E-Services Portal", type: "application", owner: "Elena Vasquez", owner_title: "CTO", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "review-needed", criticality: "critical", annual_cost: 4200, maintenance_cost: 2800, development_cost: 1400, vendor_id: "VND-005", vendor_name: "Open ePlatform", contract_end: "2026-06-30", lock_in_risk: "medium", api_reuse_potential: "high", replacement_priority: "urgent", dependencies: ["SYS-002", "SYS-005", "SYS-003"], downstream_services: ["Citizen self-service", "Building permits online", "School enrollment"], standards_used: ["STD-002", "STD-005"], linked_gov_docs: ["GOV-007", "GOV-013"], last_review_date: "2025-09-15", description: "Citizen-facing portal for all digital municipal services. Approaching EOL.", x: 400, y: 60, visibility: "public", internet_facing: true },
      { id: "SYS-002", name: "Identity Management (AD)", type: "service", owner: "Anna Lindström", owner_title: "IT Strategist", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "active", criticality: "critical", annual_cost: 1800, maintenance_cost: 1200, development_cost: 600, vendor_id: "VND-001", vendor_name: "Microsoft", contract_end: "2028-12-31", lock_in_risk: "high", api_reuse_potential: "medium", replacement_priority: "none", dependencies: ["SYS-007"], downstream_services: ["All authenticated services", "SSO", "VPN"], standards_used: ["STD-001", "STD-003"], linked_gov_docs: ["GOV-001", "GOV-004"], last_review_date: "2026-01-10", description: "Central Active Directory for all municipal authentication and authorization.", x: 180, y: 180, visibility: "internal", internet_facing: true },
      { id: "SYS-003", name: "Case Management (Procapita)", type: "application", owner: "Maria Ekberg", owner_title: "Social Services Director", department: "Social Services", org_id: "org-eskilstuna", domain: "Social Services", lifecycle: "active", criticality: "high", annual_cost: 3100, maintenance_cost: 2200, development_cost: 900, vendor_id: "VND-002", vendor_name: "CGI", contract_end: "2027-03-31", lock_in_risk: "high", api_reuse_potential: "low", replacement_priority: "planned", dependencies: ["SYS-005", "SYS-002"], downstream_services: ["Social services case handling", "Child welfare", "Elder care coordination"], standards_used: ["STD-001", "STD-004"], linked_gov_docs: ["GOV-003", "GOV-020"], last_review_date: "2025-11-20", description: "Primary case management for social services department.", x: 620, y: 180, visibility: "internal", internet_facing: false },
      { id: "SYS-004", name: "Payroll System HR+", type: "legacy", owner: "Per Johansson", owner_title: "HR Director", department: "HR", org_id: "org-eskilstuna", domain: "HR & Organization", lifecycle: "legacy", criticality: "high", annual_cost: 2400, maintenance_cost: 2100, development_cost: 300, vendor_id: "VND-003", vendor_name: "Visma", contract_end: "2026-12-31", lock_in_risk: "high", api_reuse_potential: "low", replacement_priority: "urgent", dependencies: ["SYS-005", "SYS-002"], downstream_services: ["Payroll processing", "Leave management", "Tax reporting"], standards_used: [], linked_gov_docs: ["GOV-002", "GOV-008", "GOV-017"], last_review_date: "2024-06-01", description: "Legacy COBOL-based payroll with known vulnerabilities. Replacement planned.", x: 120, y: 320, visibility: "internal", internet_facing: false },
      { id: "SYS-005", name: "SQL Server Cluster", type: "database", owner: "Anna Lindström", owner_title: "IT Strategist", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "active", criticality: "critical", annual_cost: 1600, maintenance_cost: 1100, development_cost: 500, vendor_id: "VND-001", vendor_name: "Microsoft", contract_end: "2028-06-30", lock_in_risk: "medium", api_reuse_potential: "medium", replacement_priority: "none", dependencies: ["SYS-007"], downstream_services: ["All database-dependent applications"], standards_used: ["STD-001", "STD-003"], linked_gov_docs: ["GOV-015"], last_review_date: "2026-02-01", description: "Central database cluster serving all municipal applications.", x: 400, y: 300, visibility: "internal", internet_facing: false },
      { id: "SYS-006", name: "Central File Server", type: "storage", owner: "Anna Lindström", owner_title: "IT Strategist", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "review-needed", criticality: "high", annual_cost: 800, maintenance_cost: 650, development_cost: 150, vendor_id: "VND-009", vendor_name: "Dell EMC", contract_end: "2026-09-30", lock_in_risk: "low", api_reuse_potential: "low", replacement_priority: "planned", dependencies: ["SYS-007"], downstream_services: ["Document storage", "Shared drives", "Archiving"], standards_used: ["STD-004"], linked_gov_docs: ["GOV-006"], last_review_date: "2025-08-15", description: "Central file storage at 87% capacity. Cloud migration assessment underway.", x: 660, y: 320, visibility: "internal", internet_facing: false },
      { id: "SYS-007", name: "Municipal DC (on-prem)", type: "server", owner: "Anna Lindström", owner_title: "IT Strategist", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "active", criticality: "critical", annual_cost: 5200, maintenance_cost: 4000, development_cost: 1200, vendor_id: "VND-004", vendor_name: "Dell / Cisco", contract_end: "2029-12-31", lock_in_risk: "medium", api_reuse_potential: "low", replacement_priority: "none", dependencies: [], downstream_services: ["All on-premises infrastructure"], standards_used: ["STD-003"], linked_gov_docs: ["GOV-016"], last_review_date: "2026-01-15", description: "Primary data center hosting all on-premises workloads.", x: 400, y: 440, visibility: "internal", internet_facing: false },
      { id: "SYS-008", name: "GIS Platform", type: "application", owner: "Jonas Kraft", owner_title: "Urban Planning Director", department: "Urban Planning", org_id: "org-eskilstuna", domain: "Urban Planning", lifecycle: "active", criticality: "medium", annual_cost: 1200, maintenance_cost: 800, development_cost: 400, vendor_id: "VND-006", vendor_name: "Esri / Lantmäteriet", contract_end: "2027-06-30", lock_in_risk: "medium", api_reuse_potential: "high", replacement_priority: "none", dependencies: ["SYS-005", "SYS-002"], downstream_services: ["Map services", "Spatial analysis", "Citizen map portal"], standards_used: ["STD-005"], linked_gov_docs: ["GOV-014", "GOV-019"], last_review_date: "2025-12-01", description: "Geographic information system for urban planning and public maps.", x: 80, y: 80, visibility: "public", internet_facing: true },
      { id: "SYS-009", name: "School Platform (IST)", type: "saas", owner: "Lena Berggren", owner_title: "Education Director", department: "Education & Schools", org_id: "org-eskilstuna", domain: "Education", lifecycle: "active", criticality: "high", annual_cost: 1500, maintenance_cost: 900, development_cost: 600, vendor_id: "VND-007", vendor_name: "IST", contract_end: "2027-12-31", lock_in_risk: "medium", api_reuse_potential: "medium", replacement_priority: "none", dependencies: ["SYS-002"], downstream_services: ["School administration", "Grade reporting", "Attendance"], standards_used: ["STD-005"], linked_gov_docs: ["GOV-009", "GOV-022"], last_review_date: "2026-01-20", description: "SaaS-based school administration and learning management.", x: 720, y: 80, visibility: "internal", internet_facing: false },
      { id: "SYS-010", name: "Building Permit System (ByggR)", type: "application", owner: "Jonas Kraft", owner_title: "Urban Planning Director", department: "Urban Planning", org_id: "org-eskilstuna", domain: "Urban Planning", lifecycle: "active", criticality: "medium", annual_cost: 900, maintenance_cost: 600, development_cost: 300, vendor_id: "VND-008", vendor_name: "Tekis", contract_end: "2027-09-30", lock_in_risk: "low", api_reuse_potential: "medium", replacement_priority: "none", dependencies: ["SYS-005", "SYS-008"], downstream_services: ["Building permit processing", "Inspections"], standards_used: ["STD-004"], linked_gov_docs: ["GOV-014"], last_review_date: "2025-10-01", description: "Building permit and urban planning case management.", x: 80, y: 200, visibility: "internal", internet_facing: true },
      { id: "SYS-011", name: "Email (Exchange Online)", type: "saas", owner: "Anna Lindström", owner_title: "IT Strategist", department: "IT & Digitalisation", org_id: "org-eskilstuna", domain: "IT & Digitalization", lifecycle: "active", criticality: "high", annual_cost: 2200, maintenance_cost: 1800, development_cost: 400, vendor_id: "VND-001", vendor_name: "Microsoft", contract_end: "2028-12-31", lock_in_risk: "high", api_reuse_potential: "low", replacement_priority: "none", dependencies: ["SYS-002"], downstream_services: ["Email", "Calendar", "Teams integration"], standards_used: ["STD-001"], linked_gov_docs: ["GOV-011"], last_review_date: "2026-02-15", description: "Microsoft 365 email and collaboration platform.", x: 720, y: 200, visibility: "internal", internet_facing: false },
      { id: "SYS-012", name: "Intranet (SharePoint)", type: "application", owner: "Karin Nilsson", owner_title: "Municipal Secretary", department: "Municipal Executive Office", org_id: "org-eskilstuna", domain: "Administration & Governance", lifecycle: "active", criticality: "medium", annual_cost: 600, maintenance_cost: 400, development_cost: 200, vendor_id: "VND-001", vendor_name: "Microsoft", contract_end: "2028-12-31", lock_in_risk: "medium", api_reuse_potential: "low", replacement_priority: "none", dependencies: ["SYS-002", "SYS-011"], downstream_services: ["Internal communication", "Document collaboration"], standards_used: ["STD-002"], linked_gov_docs: ["GOV-010"], last_review_date: "2025-07-01", description: "Internal staff portal and document collaboration.", x: 720, y: 320, visibility: "internal", internet_facing: false },
    ]);

    // 5. Seed risks (with previous_score for trend)
    await upsert("risks", [
      { id: "RSK-001", title: "E-Services Portal EOL", type: "end-of-life", linked_system_id: "SYS-001", likelihood: 5, impact: 5, affected_services: ["Citizen self-service", "Building permits online", "School enrollment"], owner: "Elena Vasquez", mitigation: "Migration to new platform planned for Q3 2026", due_date: "2026-06-30", escalation_status: "board", board_visibility: true, last_updated: "2026-03-01", source: "System inventory", category: "End-of-Life", org_id: "org-eskilstuna", previous_score: 20 },
      { id: "RSK-002", title: "HR+ Payroll Unpatched CVEs", type: "vulnerability", linked_system_id: "SYS-004", likelihood: 4, impact: 5, affected_services: ["Payroll processing", "Leave management", "Tax reporting"], owner: "Per Johansson", mitigation: "Legacy encapsulation strategy — WAF and network segmentation applied", due_date: "2026-09-30", escalation_status: "department", board_visibility: false, last_updated: "2026-02-15", source: "Vulnerability scan", category: "Vulnerability", org_id: "org-eskilstuna", previous_score: 15 },
      { id: "RSK-003", title: "File Server Capacity Critical", type: "capacity", linked_system_id: "SYS-006", linked_dependency: "SYS-007", likelihood: 4, impact: 4, affected_services: ["Document storage", "Shared drives", "Archiving"], owner: "Anna Lindström", mitigation: "Cloud migration assessment in progress. Temporary capacity expansion ordered.", due_date: "2026-07-15", escalation_status: "department", board_visibility: false, last_updated: "2026-03-10", source: "Monitoring", category: "Capacity", org_id: "org-eskilstuna", previous_score: 12 },
      { id: "RSK-004", title: "Procapita SSL Certificate Expiry", type: "certificate", linked_system_id: "SYS-003", likelihood: 3, impact: 4, affected_services: ["Social services case handling"], owner: "Maria Ekberg", mitigation: "Certificate renewal scheduled for April 2026", due_date: "2026-04-15", escalation_status: "none", board_visibility: false, last_updated: "2026-02-20", source: "Certificate monitoring", category: "Certificate", org_id: "org-eskilstuna", previous_score: 12 },
      { id: "RSK-005", title: "GIS Platform Load Increase", type: "capacity", linked_system_id: "SYS-008", likelihood: 3, impact: 3, affected_services: ["Map services", "Spatial analysis"], owner: "Jonas Kraft", mitigation: "Scaling planned for Q3 2026", due_date: "2026-09-01", escalation_status: "none", board_visibility: false, last_updated: "2026-01-15", source: "Performance monitoring", category: "Capacity", org_id: "org-eskilstuna", previous_score: 6 },
      { id: "RSK-006", title: "Exchange Missing GDPR Logging", type: "compliance", linked_system_id: "SYS-011", likelihood: 2, impact: 3, affected_services: ["Email compliance"], owner: "Anna Lindström", mitigation: "Microsoft Purview implementation planned Q2 2026", due_date: "2026-06-30", escalation_status: "none", board_visibility: false, last_updated: "2026-02-01", source: "Compliance audit", category: "Compliance", org_id: "org-eskilstuna", previous_score: 6 },
      { id: "RSK-007", title: "SharePoint Missing Security Patch", type: "vulnerability", linked_system_id: "SYS-012", likelihood: 3, impact: 2, affected_services: ["Internal communication"], owner: "Anna Lindström", mitigation: "Patch scheduled for next maintenance window", due_date: "2026-04-01", escalation_status: "none", board_visibility: false, last_updated: "2026-03-05", source: "Patch management", category: "Vulnerability", org_id: "org-eskilstuna", previous_score: 4 },
      { id: "RSK-008", title: "School Platform SLA Below Target", type: "availability", linked_system_id: "SYS-009", likelihood: 2, impact: 2, affected_services: ["School administration", "Grade reporting"], owner: "Lena Berggren", mitigation: "Vendor SLA renegotiation in progress", due_date: "2026-05-31", escalation_status: "none", board_visibility: false, last_updated: "2026-03-01", source: "SLA monitoring", category: "Availability", org_id: "org-eskilstuna", previous_score: 6 },
      { id: "RSK-009", title: "Single Point of Failure — Municipal DC", type: "single-point-of-failure", linked_system_id: "SYS-007", likelihood: 2, impact: 5, affected_services: ["All on-premises infrastructure"], owner: "Anna Lindström", mitigation: "DR site assessment completed. Backup DC proposal submitted to board.", due_date: "2027-01-01", escalation_status: "board", board_visibility: true, last_updated: "2026-02-20", source: "Infrastructure audit", category: "Single Point of Failure", org_id: "org-eskilstuna", previous_score: 10 },
      { id: "RSK-010", title: "AD — No Reviewed MFA Policy for Admin Accounts", type: "vulnerability", linked_system_id: "SYS-002", likelihood: 3, impact: 5, affected_services: ["All authenticated services", "SSO"], owner: "Anna Lindström", mitigation: "MFA enforcement for admin accounts planned Q2 2026", due_date: "2026-06-01", escalation_status: "department", board_visibility: false, last_updated: "2026-03-12", source: "Security audit", category: "Vulnerability", org_id: "org-eskilstuna", previous_score: 15 },
      { id: "RSK-011", title: "Legacy Dependencies in Case Management", type: "end-of-life", linked_system_id: "SYS-003", linked_dependency: "SYS-004", likelihood: 3, impact: 4, affected_services: ["Social services case handling", "Payroll integration"], owner: "Maria Ekberg", mitigation: "Dependency mapping and decoupling strategy in progress", due_date: "2026-12-31", escalation_status: "none", board_visibility: false, last_updated: "2026-01-20", source: "Dependency analysis", category: "End-of-Life", org_id: "org-eskilstuna", previous_score: 9 },
      { id: "RSK-012", title: "No Disaster Recovery for SQL Cluster", type: "single-point-of-failure", linked_system_id: "SYS-005", linked_dependency: "SYS-007", likelihood: 2, impact: 5, affected_services: ["All database-dependent applications"], owner: "Anna Lindström", mitigation: "Offsite replication setup planned for H2 2026", due_date: "2026-12-31", escalation_status: "board", board_visibility: true, last_updated: "2026-02-28", source: "DR assessment", category: "Single Point of Failure", org_id: "org-eskilstuna", previous_score: 10 },
    ]);

    // 6. Seed APIs (with developer_municipality & developer_contact for partner APIs)
    await upsert("apis", [
      { id: "API-001", name: "E-Services REST API", type: "internal", linked_system_id: "SYS-001", protocol: "REST", description: "Core API for citizen-facing e-services portal", endpoint: "/api/v1/eservices", problems_solved: ["Digital service delivery", "Citizen self-service", "Form submission automation"], org_id: "org-eskilstuna", visibility: "internal", authentication: "OAuth2 + Service Account", version: "v2.1", rate_limit_per_min: 200 },
      { id: "API-002", name: "AD Authentication API", type: "internal", linked_system_id: "SYS-002", protocol: "LDAP/REST", description: "Authentication and authorization for all municipal systems", endpoint: "/api/v1/auth", problems_solved: ["Single sign-on", "Identity management", "Access control"], org_id: "org-eskilstuna", visibility: "internal", authentication: "mTLS + Kerberos", version: "v1.4", rate_limit_per_min: 500 },
      { id: "API-003", name: "Procapita Integration API", type: "internal", linked_system_id: "SYS-003", protocol: "SOAP", description: "Case management data exchange for social services", endpoint: "/api/v1/cases", problems_solved: ["Case data integration", "Social services workflow", "Cross-department case sharing"], org_id: "org-eskilstuna", visibility: "internal", authentication: "WS-Security", version: "v1.0", rate_limit_per_min: 50 },
      { id: "API-004", name: "Database Gateway", type: "internal", linked_system_id: "SYS-005", protocol: "REST", description: "Central data access layer for SQL cluster", endpoint: "/api/v1/data", problems_solved: ["Data access standardization", "Query optimization", "Connection pooling"], org_id: "org-eskilstuna", visibility: "internal", authentication: "Service Account", version: "v3.0", rate_limit_per_min: 1000 },
      { id: "API-005", name: "BankID Integration", type: "partner", linked_system_id: "SYS-001", protocol: "REST", description: "Swedish electronic identification for secure citizen authentication", endpoint: "/api/v1/bankid", problems_solved: ["Citizen identity verification", "Secure authentication", "Digital signing"], org_id: "org-eskilstuna", visibility: "partner", authentication: "API Key + mTLS", version: "v6.0", rate_limit_per_min: 300, developer_municipality: "BankID (National)", developer_contact: "support@bankid.com" },
      { id: "API-006", name: "GIS Map Service", type: "public", linked_system_id: "SYS-008", protocol: "REST/WMS", description: "Public geographic data and map services for citizens and developers", endpoint: "/api/v1/maps", problems_solved: ["Public map access", "Spatial data queries", "Urban planning transparency"], org_id: "org-eskilstuna", visibility: "public", authentication: "Rate-limited / Anonymous", version: "v2.0", rate_limit_per_min: 100 },
      { id: "API-007", name: "IST School Data API", type: "partner", linked_system_id: "SYS-009", protocol: "REST", description: "School administration data exchange with IST platform", endpoint: "/api/v1/school", problems_solved: ["School data integration", "Attendance tracking", "Grade reporting"], org_id: "org-eskilstuna", visibility: "partner", authentication: "OAuth2", version: "v2.3", rate_limit_per_min: 150, developer_municipality: "Stockholm Municipality", developer_contact: "digital@stockholm.se" },
      { id: "API-008", name: "Building Permit API", type: "public", linked_system_id: "SYS-010", protocol: "REST", description: "Public API for building permit applications and status tracking", endpoint: "/api/v1/permits", problems_solved: ["Permit application tracking", "Digital permit submission", "Status transparency"], org_id: "org-eskilstuna", visibility: "public", authentication: "BankID for submissions / Anonymous for queries", version: "v1.2", rate_limit_per_min: 60 },
      { id: "API-009", name: "Microsoft Graph API", type: "partner", linked_system_id: "SYS-011", protocol: "REST", description: "Integration with Microsoft 365 services for email and collaboration", endpoint: "https://graph.microsoft.com/v1.0", problems_solved: ["Email integration", "Calendar sync", "Teams automation"], org_id: "org-eskilstuna", visibility: "partner", authentication: "OAuth2 + Azure AD", version: "v1.0", rate_limit_per_min: 120, developer_municipality: "Microsoft (Global)", developer_contact: "enterprise@microsoft.com" },
      { id: "API-010", name: "HR+ Payroll Integration API", type: "internal", linked_system_id: "SYS-004", protocol: "REST", description: "Payroll data exchange, leave management, and tax reporting integration", endpoint: "/api/v1/payroll", problems_solved: ["Payroll automation", "Tax reporting", "Leave tracking"], org_id: "org-eskilstuna", visibility: "internal", authentication: "Service Account + VPN", version: "v1.1", rate_limit_per_min: 30 },
      { id: "API-011", name: "Document Management API", type: "internal", linked_system_id: "SYS-006", protocol: "REST/WebDAV", description: "Central file storage CRUD operations and metadata management", endpoint: "/api/v1/documents", problems_solved: ["File storage abstraction", "Metadata search", "Version control"], org_id: "org-eskilstuna", visibility: "internal", authentication: "OAuth2", version: "v1.0", rate_limit_per_min: 200 },
      { id: "API-012", name: "Intranet Content API", type: "internal", linked_system_id: "SYS-012", protocol: "REST", description: "SharePoint content and news feed API for internal communication", endpoint: "/api/v1/intranet", problems_solved: ["Internal news distribution", "Document collaboration", "Staff directory"], org_id: "org-eskilstuna", visibility: "internal", authentication: "Azure AD OAuth2", version: "v2.0", rate_limit_per_min: 150 },
      { id: "API-013", name: "Infrastructure Monitoring API", type: "internal", linked_system_id: "SYS-007", protocol: "REST", description: "Real-time server health metrics, alerts, and capacity monitoring", endpoint: "/api/v1/monitoring", problems_solved: ["Server health monitoring", "Capacity planning", "Alert management"], org_id: "org-eskilstuna", visibility: "internal", authentication: "API Key", version: "v1.3", rate_limit_per_min: 500 },
      { id: "API-014", name: "ChatBot NLP API", type: "internal", linked_system_id: "SYS-001", protocol: "REST", description: "Natural language processing for citizen chatbot on e-services portal", endpoint: "/api/v1/nlp", problems_solved: ["Citizen query routing", "FAQ automation", "Multi-language support"], org_id: "org-eskilstuna", visibility: "internal", authentication: "API Key", version: "v1.0", rate_limit_per_min: 100 },
      { id: "API-015", name: "Skatteverket Tax Reporting API", type: "partner", linked_system_id: "SYS-004", protocol: "REST/XML", description: "Swedish Tax Agency integration for employer tax declarations and employee data", endpoint: "https://api.skatteverket.se/v1/employer", problems_solved: ["Tax declaration automation", "Employee data sync", "Compliance reporting"], org_id: "org-eskilstuna", visibility: "partner", authentication: "mTLS + Certificate", version: "v3.1", rate_limit_per_min: 20, developer_municipality: "Skatteverket (National)", developer_contact: "api@skatteverket.se" },
      { id: "API-016", name: "Region Sörmland Health Data API", type: "partner", linked_system_id: "SYS-003", protocol: "HL7/FHIR", description: "Regional health data exchange for integrated social and health care", endpoint: "https://api.regionsormland.se/fhir/v1", problems_solved: ["Health-social care coordination", "Patient data sharing", "Regional statistics"], org_id: "org-eskilstuna", visibility: "partner", authentication: "OAuth2 + SITHS", version: "v1.0", rate_limit_per_min: 50, developer_municipality: "Region Sörmland", developer_contact: "ehealth@regionsormland.se" },
      { id: "API-017", name: "Lantmäteriet Property Data API", type: "partner", linked_system_id: "SYS-008", protocol: "REST", description: "National land survey property and cadastral data for building permits and planning", endpoint: "https://api.lantmateriet.se/v2/property", problems_solved: ["Property boundary data", "Land ownership verification", "Cadastral integration"], org_id: "org-eskilstuna", visibility: "partner", authentication: "API Key", version: "v2.0", rate_limit_per_min: 60, developer_municipality: "Lantmäteriet (National)", developer_contact: "api@lantmateriet.se" },
      { id: "API-018", name: "DIGG Digital Mail API", type: "partner", linked_system_id: "SYS-001", protocol: "REST", description: "Swedish Digital Government Agency secure digital mail for citizen communication", endpoint: "https://api.digg.se/v1/digitalmail", problems_solved: ["Secure citizen notifications", "Digital postal replacement", "GDPR-compliant communication"], org_id: "org-eskilstuna", visibility: "partner", authentication: "mTLS + OAuth2", version: "v1.2", rate_limit_per_min: 100, developer_municipality: "Sundsvall Municipality", developer_contact: "digital@sundsvall.se" },
      { id: "API-019", name: "Open Budget Data API", type: "public", linked_system_id: null, protocol: "REST", description: "Municipal budget allocations, spending data, and financial reports for transparency", endpoint: "/api/v1/budget", problems_solved: ["Budget transparency", "Financial accountability", "Open government data"], org_id: "org-eskilstuna", visibility: "public", authentication: "None", version: "v1.0", rate_limit_per_min: 60 },
      { id: "API-020", name: "Waste Collection Schedule API", type: "public", linked_system_id: null, protocol: "REST", description: "Garbage and recycling pickup schedules, recycling station locations", endpoint: "/api/v1/waste", problems_solved: ["Waste pickup scheduling", "Recycling station finder", "Environmental data access"], org_id: "org-eskilstuna", visibility: "public", authentication: "None", version: "v1.2", rate_limit_per_min: 100 },
      { id: "API-021", name: "Cultural Events API", type: "public", linked_system_id: null, protocol: "REST", description: "Upcoming events from municipal cultural institutions, libraries, and museums", endpoint: "/api/v1/events", problems_solved: ["Event discovery", "Cultural programming", "Community engagement"], org_id: "org-eskilstuna", visibility: "public", authentication: "None", version: "v1.1", rate_limit_per_min: 100 },
      { id: "API-022", name: "School Performance Data API", type: "public", linked_system_id: "SYS-009", protocol: "REST", description: "Anonymized school performance metrics, class sizes, and satisfaction scores", endpoint: "/api/v1/schools/performance", problems_solved: ["Education transparency", "School comparison data", "Parent information access"], org_id: "org-eskilstuna", visibility: "public", authentication: "None", version: "v2.0", rate_limit_per_min: 60 },
    ]);

    // 7. Seed governance documents
    const today = new Date();
    const daysFromNow = (d: number) => {
      const date = new Date(today);
      date.setDate(date.getDate() + d);
      return date.toISOString().split("T")[0];
    };

    await upsert("governance_documents", [
      { id: "GOV-001", title: "Riktlinje för informationssäkerhet", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Operational", category: "Information Security", review_date: daysFromNow(-45), status: "Active", org_id: "org-eskilstuna", created_date: "2022-03-15", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-003"], linked_core_systems: ["SYS-001", "SYS-003"], escalated_to_board: false, strategic_goals: ["Stärkt informationssäkerhet och GDPR-efterlevnad"], keywords: ["information security", "policy", "data protection", "IT"], domain: "IT & Digitalization" },
      { id: "GOV-002", title: "Policy för distansarbete", owner: "Per Johansson", owner_title: "HR-chef", unit: "HR-avdelningen", classification: "Operational", category: "HR Policy", review_date: daysFromNow(14), status: "Active", org_id: "org-eskilstuna", created_date: "2023-01-10", security_checks: { gdpr: true, dataMin: true, audit: false, tls: true, oauth: false, separation: false, centralized: false }, linked_standards: ["STD-002"], linked_core_systems: ["SYS-002"], escalated_to_board: false, strategic_goals: ["Effektivisering av interna administrativa processer"], keywords: ["remote work", "HR", "work policy"], domain: "HR & Organization" },
      { id: "GOV-003", title: "Rutin för ärendehandläggning inom socialtjänsten", owner: "Maria Ekberg", owner_title: "Socialchef", unit: "Socialförvaltningen", classification: "Operational", category: "Case Management", review_date: daysFromNow(90), status: "Active", org_id: "org-eskilstuna", created_date: "2023-06-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-004"], linked_core_systems: ["SYS-004"], escalated_to_board: false, strategic_goals: ["Effektivisering av interna administrativa processer"], keywords: ["case management", "social services"], domain: "Social Services" },
      { id: "GOV-004", title: "Digitaliseringsstrategi 2024–2027", owner: "Elena Vasquez", owner_title: "CTO", unit: "Kommunstyrelseförvaltningen", classification: "Development/Innovation", category: "Digital Strategy", review_date: daysFromNow(180), status: "Active", org_id: "org-eskilstuna", created_date: "2024-01-15", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-002", "STD-003"], linked_core_systems: ["SYS-001", "SYS-002", "SYS-003"], escalated_to_board: true, strategic_goals: ["Ökad digital tillgänglighet för invånare", "Hållbar samhällsutveckling och digitalisering"], keywords: ["digitalization", "strategy", "innovation"], domain: "IT & Digitalization" },
      { id: "GOV-005", title: "Riktlinje för upphandling av IT-system", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Operational", category: "Procurement", review_date: daysFromNow(60), status: "Active", org_id: "org-eskilstuna", created_date: "2022-09-01", security_checks: { gdpr: true, dataMin: false, audit: true, tls: true, oauth: false, separation: true, centralized: false }, linked_standards: ["STD-003"], linked_core_systems: ["SYS-001"], escalated_to_board: false, strategic_goals: ["Effektivisering av interna administrativa processer"], keywords: ["procurement", "IT systems"], domain: "IT & Digitalization" },
      { id: "GOV-006", title: "Arkivreglemente för digitala handlingar", owner: "Karin Nilsson", owner_title: "Kommunsekreterare", unit: "Kommunstyrelseförvaltningen", classification: "Operational", category: "Archiving", review_date: daysFromNow(120), status: "Active", org_id: "org-eskilstuna", created_date: "2021-11-20", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: false, centralized: true }, linked_standards: ["STD-004"], linked_core_systems: ["SYS-005"], escalated_to_board: false, strategic_goals: ["Stärkt informationssäkerhet och GDPR-efterlevnad"], keywords: ["archive", "digital records"], domain: "Administration & Governance" },
      { id: "GOV-007", title: "Rutin för tillgänglighetsanpassning av digitala tjänster", owner: "Elena Vasquez", owner_title: "CTO", unit: "IT- och digitaliseringsenheten", classification: "Development/Innovation", category: "Accessibility", review_date: daysFromNow(45), status: "Active", org_id: "org-eskilstuna", created_date: "2023-04-01", security_checks: { gdpr: true, dataMin: true, audit: false, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-002", "STD-005"], linked_core_systems: ["SYS-001", "SYS-006"], escalated_to_board: false, strategic_goals: ["Ökad digital tillgänglighet för invånare"], keywords: ["accessibility", "WCAG"], domain: "IT & Digitalization" },
      { id: "GOV-008", title: "Policy mot kränkande särbehandling", owner: "Per Johansson", owner_title: "HR-chef", unit: "HR-avdelningen", classification: "Operational", category: "HR Policy", review_date: daysFromNow(200), status: "Active", org_id: "org-eskilstuna", created_date: "2022-05-15", security_checks: { gdpr: true, dataMin: true, audit: true, tls: false, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: ["SYS-002"], escalated_to_board: false, strategic_goals: [], keywords: ["harassment", "workplace"], domain: "HR & Organization" },
      { id: "GOV-009", title: "Plan för systematiskt kvalitetsarbete i skolan", owner: "Lena Berggren", owner_title: "Utbildningschef", unit: "Barn- och utbildningsförvaltningen", classification: "Operational", category: "Quality Assurance", review_date: daysFromNow(30), status: "Active", org_id: "org-eskilstuna", created_date: "2023-08-20", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: false, centralized: true }, linked_standards: ["STD-005"], linked_core_systems: ["SYS-009"], escalated_to_board: false, strategic_goals: ["Hållbar samhällsutveckling och digitalisering"], keywords: ["quality", "education"], domain: "Education" },
      { id: "GOV-010", title: "Riktlinje för sociala medier", owner: "Karin Nilsson", owner_title: "Kommunsekreterare", unit: "Kommunstyrelseförvaltningen", classification: "Operational", category: "Communication", review_date: daysFromNow(-30), status: "Active", org_id: "org-eskilstuna", created_date: "2021-06-10", security_checks: { gdpr: false, dataMin: false, audit: false, tls: true, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: [], escalated_to_board: false, strategic_goals: ["Ökad digital tillgänglighet för invånare"], keywords: ["social media", "communication"], domain: "Administration & Governance" },
      { id: "GOV-011", title: "GDPR-policy för hantering av personuppgifter", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Operational", category: "GDPR Compliance", review_date: daysFromNow(-60), status: "Active", org_id: "org-eskilstuna", created_date: "2020-05-25", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-004"], linked_core_systems: ["SYS-001", "SYS-003", "SYS-004"], escalated_to_board: true, strategic_goals: ["Stärkt informationssäkerhet och GDPR-efterlevnad"], keywords: ["GDPR", "personal data", "privacy"], domain: "IT & Digitalization" },
      { id: "GOV-012", title: "Riktlinje för IT-upphandling (äldre version)", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Operational", category: "Procurement", review_date: daysFromNow(-120), status: "Active", org_id: "org-eskilstuna", created_date: "2019-03-01", security_checks: { gdpr: false, dataMin: false, audit: true, tls: true, oauth: false, separation: false, centralized: false }, linked_standards: ["STD-003"], linked_core_systems: ["SYS-001"], escalated_to_board: false, strategic_goals: [], keywords: ["procurement", "legacy"], domain: "IT & Digitalization" },
      { id: "GOV-013", title: "Strategi för e-tjänster och medborgardialog", owner: "Elena Vasquez", owner_title: "CTO", unit: "Kommunstyrelseförvaltningen", classification: "Development/Innovation", category: "Digital Strategy", review_date: daysFromNow(150), status: "Active", org_id: "org-eskilstuna", created_date: "2024-02-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-002", "STD-005"], linked_core_systems: ["SYS-001", "SYS-006"], escalated_to_board: true, strategic_goals: ["Ökad digital tillgänglighet för invånare", "Hållbar samhällsutveckling och digitalisering"], keywords: ["e-services", "citizen dialogue"], domain: "IT & Digitalization" },
      { id: "GOV-014", title: "Policy för handläggning av bygglov", owner: "Jonas Kraft", owner_title: "Stadsbyggnadschef", unit: "Stadsbyggnadsförvaltningen", classification: "Operational", category: "Case Management", review_date: daysFromNow(75), status: "Active", org_id: "org-eskilstuna", created_date: "2022-11-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: true, centralized: false }, linked_standards: ["STD-004"], linked_core_systems: ["SYS-008"], escalated_to_board: false, strategic_goals: ["Effektivisering av interna administrativa processer"], keywords: ["building permit"], domain: "Urban Planning" },
      { id: "GOV-015", title: "Riktlinje för molntjänster och datalagring", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Development/Innovation", category: "IT Governance", review_date: daysFromNow(25), status: "Active", org_id: "org-eskilstuna", created_date: "2023-10-15", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-003"], linked_core_systems: ["SYS-001", "SYS-003"], escalated_to_board: false, strategic_goals: ["Stärkt informationssäkerhet och GDPR-efterlevnad"], keywords: ["cloud", "data storage"], domain: "IT & Digitalization" },
      { id: "GOV-016", title: "Handlingsplan för krisberedskap", owner: "Karin Nilsson", owner_title: "Kommunsekreterare", unit: "Kommunstyrelseförvaltningen", classification: "Operational", category: "Quality Assurance", review_date: daysFromNow(210), status: "Active", org_id: "org-eskilstuna", created_date: "2023-03-01", security_checks: { gdpr: true, dataMin: false, audit: true, tls: true, oauth: false, separation: true, centralized: true }, linked_standards: [], linked_core_systems: ["SYS-007"], escalated_to_board: false, strategic_goals: [], keywords: ["crisis", "emergency"], domain: "Administration & Governance" },
      { id: "GOV-017", title: "Rutin för introduktion av nyanställda", owner: "Per Johansson", owner_title: "HR-chef", unit: "HR-avdelningen", classification: "Operational", category: "HR Policy", review_date: daysFromNow(90), status: "Active", org_id: "org-eskilstuna", created_date: "2023-09-01", security_checks: { gdpr: true, dataMin: true, audit: false, tls: false, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: ["SYS-002"], escalated_to_board: false, strategic_goals: ["Effektivisering av interna administrativa processer"], keywords: ["onboarding", "new employees"], domain: "HR & Organization" },
      { id: "GOV-018", title: "Policy för öppen data", owner: "Elena Vasquez", owner_title: "CTO", unit: "IT- och digitaliseringsenheten", classification: "Development/Innovation", category: "Data Management", review_date: daysFromNow(100), status: "Active", org_id: "org-eskilstuna", created_date: "2024-03-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001", "STD-002"], linked_core_systems: ["SYS-001"], escalated_to_board: false, strategic_goals: ["Ökad digital tillgänglighet för invånare"], keywords: ["open data", "transparency"], domain: "IT & Digitalization" },
      { id: "GOV-019", title: "Riktlinje för detaljplanering", owner: "Jonas Kraft", owner_title: "Stadsbyggnadschef", unit: "Stadsbyggnadsförvaltningen", classification: "Operational", category: "Case Management", review_date: daysFromNow(140), status: "Active", org_id: "org-eskilstuna", created_date: "2022-07-15", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: true, centralized: false }, linked_standards: ["STD-004"], linked_core_systems: ["SYS-008"], escalated_to_board: false, strategic_goals: ["Hållbar samhällsutveckling och digitalisering"], keywords: ["detailed planning"], domain: "Urban Planning" },
      { id: "GOV-020", title: "Handlingsplan för digital social omsorg", owner: "", owner_title: "", unit: "Socialförvaltningen", classification: "Development/Innovation", category: "Digital Strategy", review_date: daysFromNow(-15), status: "Draft", org_id: "org-eskilstuna", created_date: "2025-06-01", security_checks: { gdpr: false, dataMin: false, audit: false, tls: false, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: [], escalated_to_board: false, strategic_goals: [], keywords: ["social care", "digital"], domain: "Social Services", has_owner: false },
      { id: "GOV-021", title: "Riktlinje för intern kommunikation", owner: "", owner_title: "", unit: "Kommunstyrelseförvaltningen", classification: "Operational", category: "Communication", review_date: daysFromNow(-90), status: "Active", org_id: "org-eskilstuna", created_date: "2020-01-15", security_checks: { gdpr: false, dataMin: false, audit: false, tls: false, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: [], escalated_to_board: false, strategic_goals: [], keywords: ["communication", "internal"], domain: "Administration & Governance", has_owner: false },
      { id: "GOV-022", title: "Policy för digital undervisning", owner: "Lena Berggren", owner_title: "Utbildningschef", unit: "Barn- och utbildningsförvaltningen", classification: "Development/Innovation", category: "Digital Strategy", review_date: daysFromNow(200), status: "Active", org_id: "org-eskilstuna", created_date: "2024-08-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: false, separation: false, centralized: true }, linked_standards: ["STD-005"], linked_core_systems: ["SYS-009"], escalated_to_board: false, strategic_goals: ["Ökad digital tillgänglighet för invånare"], keywords: ["education", "digital"], domain: "Education" },
      { id: "GOV-023", title: "Rutin för hantering av läkemedel i äldreomsorgen", owner: "", owner_title: "", unit: "Socialförvaltningen", classification: "Operational", category: "Quality Assurance", review_date: daysFromNow(-180), status: "Active", org_id: "org-eskilstuna", created_date: "2019-04-10", security_checks: { gdpr: true, dataMin: false, audit: false, tls: false, oauth: false, separation: false, centralized: false }, linked_standards: [], linked_core_systems: [], escalated_to_board: false, strategic_goals: [], keywords: ["medication", "elder care"], domain: "Social Services", has_owner: false },
      { id: "GOV-024", title: "Dataskyddsombud — årsrapport 2024", owner: "Anna Lindström", owner_title: "IT-strateg", unit: "IT- och digitaliseringsenheten", classification: "Operational", category: "GDPR Compliance", review_date: daysFromNow(-200), status: "Archived", org_id: "org-eskilstuna", created_date: "2024-12-01", security_checks: { gdpr: true, dataMin: true, audit: true, tls: true, oauth: true, separation: true, centralized: true }, linked_standards: ["STD-001"], linked_core_systems: [], escalated_to_board: false, strategic_goals: ["Stärkt informationssäkerhet och GDPR-efterlevnad"], keywords: ["GDPR", "DPO", "annual report"], domain: "IT & Digitalization" },
    ]);

    // 8. Seed contradictions
    await upsert("governance_contradictions", [
      { id: "CON-001", doc_a_id: "GOV-005", doc_b_id: "GOV-012", description: "GOV-005 requires open competitive bidding for IT procurement, while GOV-012 allows direct vendor selection for contracts under 500 kSEK.", explanation: "These two procurement policies create ambiguity for contracts in the 200-500 kSEK range.", severity: "High", resolved: false, org_id: "org-eskilstuna", rule_conflict: "GOV-005 §4.2 sets threshold at 200 kSEK for competitive bidding. GOV-012 §3.1 allows direct selection up to 500 kSEK.", why_matters: "Departments citing the older policy bypass competitive procurement requirements, reducing cost efficiency and increasing vendor lock-in risk.", review_next: "1) Archive GOV-012 and designate GOV-005 as the sole active procurement policy. 2) Update GOV-005 to address the direct selection threshold explicitly." },
      { id: "CON-002", doc_a_id: "GOV-001", doc_b_id: "GOV-002", description: "Information security policy requires centralized audit logging, but the remote work policy does not address logging of VPN and remote access sessions.", explanation: "Without mandatory VPN session logging during remote work, the municipality cannot fully comply with its own information security baseline.", severity: "Medium", resolved: false, org_id: "org-eskilstuna", rule_conflict: "GOV-001 §5.3 mandates centralized audit logging for all access. GOV-002 §2.1 does not include VPN/remote sessions in its scope.", why_matters: "During remote work audits, 34% of VPN sessions had no corresponding audit log entries.", review_next: "1) Amend GOV-002 to explicitly include VPN session logging requirements. 2) Configure VPN gateway to forward session logs to the central SIEM." },
      { id: "CON-003", doc_a_id: "GOV-011", doc_b_id: "GOV-010", description: "GDPR policy requires data minimization in all communications, but social media guidelines allow broad data collection for engagement analytics.", explanation: "The social media team collects engagement metrics including IP-based location data, which conflicts with data minimization requirements.", severity: "High", resolved: false, org_id: "org-eskilstuna", rule_conflict: "GOV-011 §3.2 requires data minimization across all channels. GOV-010 §4.5 permits engagement analytics without specifying anonymization.", why_matters: "IP-based location tracking on municipal social media pages may constitute processing of personal data without proper legal basis.", review_next: "1) Conduct a DPIA on social media analytics. 2) Amend GOV-010 to require anonymized analytics only." },
      { id: "CON-004", doc_a_id: "GOV-015", doc_b_id: "GOV-011", description: "Cloud services guideline permits data processing in EEA countries, while GDPR policy requires all personal data to be stored within Sweden or EU.", explanation: "GOV-015 extends acceptable jurisdictions to EEA while GOV-011 limits to EU member states.", severity: "Medium", resolved: false, org_id: "org-eskilstuna", rule_conflict: "GOV-015 §2.4 permits 'EEA countries'. GOV-011 §4.1 restricts to 'EU member states'. EEA includes non-EU countries.", why_matters: "Two cloud services currently process Swedish personal data in Norway-based data centers.", review_next: "1) Align terminology: decide whether 'EEA' or 'EU' is the correct scope. 2) Review cloud contracts for actual data residency guarantees." },
    ]);

    // 9. Seed governance standards
    await upsert("governance_standards", [
      { id: "STD-001", name: "ISO 27001", description: "International standard for information security management systems", status: "Active", linked_doc_ids: ["GOV-001", "GOV-003", "GOV-011", "GOV-015", "GOV-018", "GOV-024"], org_id: "org-eskilstuna" },
      { id: "STD-002", name: "WCAG 2.1 AA", description: "Web Content Accessibility Guidelines for digital services", status: "Active", linked_doc_ids: ["GOV-002", "GOV-007", "GOV-013", "GOV-018"], org_id: "org-eskilstuna" },
      { id: "STD-003", name: "SS-ISO/IEC 27002", description: "Code of practice for information security controls", status: "Active", linked_doc_ids: ["GOV-001", "GOV-004", "GOV-005", "GOV-012", "GOV-015"], org_id: "org-eskilstuna" },
      { id: "STD-004", name: "OAIS (ISO 14721)", description: "Open Archival Information System standard for digital preservation", status: "Active", linked_doc_ids: ["GOV-003", "GOV-006", "GOV-014", "GOV-019"], org_id: "org-eskilstuna" },
      { id: "STD-005", name: "DIGG Digital First", description: "Swedish Agency for Digital Government guidelines for digital services", status: "Active", linked_doc_ids: ["GOV-007", "GOV-009", "GOV-013", "GOV-022"], org_id: "org-eskilstuna" },
      { id: "STD-006", name: "NIS2 Directive", description: "EU directive on cybersecurity requirements for essential services", status: "Draft", linked_doc_ids: [], org_id: "org-eskilstuna" },
    ]);

    // 10. Seed knowledge hub items
    await upsert("knowledge_ideas", [
      { id: "idea-1", title: "Automatic Meeting Minutes", description: "AI-powered transcription and summarisation of internal meetings.", department: "IT & Digitalisation", contact_name: "Anna Lindström", contact_email: "anna.lindstrom@eskilstuna.se", date_submitted: "2026-01-15", status: "under-experiment", classification: "efficiency", org_id: "org-eskilstuna" },
      { id: "idea-2", title: "Digital Building Permit Submission", description: "Self-service portal for citizens to submit and track building permit applications digitally.", department: "Urban Planning & Environment", contact_name: "Elena Vasquez", contact_email: "elena@eskilstuna.demo", date_submitted: "2025-09-03", status: "published", classification: "transformation", org_id: "org-eskilstuna" },
      { id: "idea-3", title: "Chatbot for Social Services Enquiries", description: "An AI chatbot to handle initial citizen enquiries to social services.", department: "Social Services", contact_name: "Maria Ekberg", contact_email: "maria.ekberg@eskilstuna.se", date_submitted: "2026-02-28", status: "awaiting-review", classification: "innovation", org_id: "org-eskilstuna" },
      { id: "idea-4", title: "Predictive Absence Analysis in Schools", description: "Machine learning model to predict and prevent student absences.", department: "Education & Schools", contact_name: "Per Johansson", contact_email: "per.johansson@eskilstuna.se", date_submitted: "2026-02-10", status: "standard-process", classification: "innovation", org_id: "org-eskilstuna" },
      { id: "idea-5", title: "Automated Scheduling for Home Care Services", description: "Optimised scheduling algorithm for home care visits.", department: "Social Services", contact_name: "Karin Nilsson", contact_email: "karin.nilsson@eskilstuna.se", date_submitted: "2025-11-20", status: "closed", classification: "efficiency", org_id: "org-eskilstuna" },
      { id: "idea-6", title: "Real-time Traffic Flow Dashboard", description: "IoT-based dashboard for monitoring traffic signals and pedestrian flows.", department: "Urban Planning & Environment", contact_name: "Jonas Kraft", contact_email: "jonas.kraft@eskilstuna.se", date_submitted: "2026-03-01", status: "awaiting-review", classification: "innovation", org_id: "org-eskilstuna" },
      { id: "idea-7", title: "Centralized Document Translation Service", description: "Automated translation of municipal documents into the top 10 resident languages.", department: "Municipal Executive Office", contact_name: "Karin Nilsson", contact_email: "karin.nilsson@eskilstuna.se", date_submitted: "2026-03-05", status: "awaiting-review", classification: "maintenance", org_id: "org-eskilstuna" },
    ]);

    await upsert("knowledge_experiments", [
      { id: "exp-1", idea_id: "idea-1", title: "Automatic Meeting Minutes", owner: "Anna Lindström", department: "IT & Digitalisation", started_weeks_ago: 3, timebox_weeks: 10, sandbox_weeks: 10, progress_percent: 30, tags: ["#internal-tools", "#loosely-coupled"], isolated: true, no_production_access: true, mock_data_only: true, hypothesis: "Automated meeting minutes will reduce administrative overhead by 60%.", observations: "Initial tests show accurate transcription for Swedish.", completed: false, classification: "efficiency", visibility: "internal", org_id: "org-eskilstuna", fast_track: false, approval_status: "approved", approver: "Elena Vasquez", exit_log_approved: false },
      { id: "exp-2", idea_id: "idea-2", title: "Digital Building Permit Submission", owner: "Elena Vasquez", department: "Urban Planning & Environment", started_weeks_ago: 20, timebox_weeks: 12, sandbox_weeks: 12, progress_percent: 100, tags: ["#citizen-services", "#self-service"], isolated: true, no_production_access: true, mock_data_only: false, hypothesis: "Self-service building permit submission will reduce processing time by 30%.", observations: "Citizens adopted digital submission at a higher rate than expected.", completed: true, result: "Processing time reduced by 41% — exceeded expectations.", divergence: "Paper applications dropped by 67%.", recommendation: "scale", apis_used: ["Eskilstuna Open Data API", "BankID integration"], system_impact: "Building permit system Castor connected via REST API.", classification: "transformation", visibility: "public", org_id: "org-eskilstuna", fast_track: false, approval_status: "approved", approver: "Jonas Kraft", exit_log_approved: true, outcome_routing: "scale" },
      // Fast Track experiments
      { id: "exp-ft-1", idea_id: "idea-6", title: "Traffic Flow Sensor Prototype", owner: "Jonas Kraft", department: "Urban Planning & Environment", started_weeks_ago: 2, timebox_weeks: 8, sandbox_weeks: 8, progress_percent: 25, tags: ["#iot", "#loosely-coupled", "#fast-track"], isolated: true, no_production_access: true, mock_data_only: true, hypothesis: "IoT sensors can provide real-time traffic data at 80% accuracy vs manual counts.", observations: "Sensor placement at 3 intersections. Initial accuracy 72%.", completed: false, classification: "innovation", visibility: "internal", org_id: "org-eskilstuna", fast_track: true, sandbox_start_date: "2026-03-03", approval_status: "approved", approver: "Elena Vasquez", exit_log_approved: false },
      { id: "exp-ft-2", idea_id: "idea-3", title: "Social Services Chatbot MVP", owner: "Maria Ekberg", department: "Social Services", started_weeks_ago: 6, timebox_weeks: 10, sandbox_weeks: 10, progress_percent: 60, tags: ["#ai", "#citizen-services", "#fast-track"], isolated: true, no_production_access: true, mock_data_only: true, hypothesis: "An NLP chatbot can correctly route 70% of initial social services enquiries.", observations: "Accuracy at 65% with Swedish language model. Needs more training data.", completed: false, classification: "innovation", visibility: "internal", org_id: "org-eskilstuna", fast_track: true, sandbox_start_date: "2026-02-03", approval_status: "approved", approver: "Elena Vasquez", exit_log_approved: false },
      { id: "exp-ft-3", title: "Automated Document Translation", owner: "Karin Nilsson", department: "Municipal Executive Office", started_weeks_ago: 12, timebox_weeks: 10, progress_percent: 100, tags: ["#translation", "#ai", "#fast-track"], isolated: true, no_production_access: true, mock_data_only: false, hypothesis: "Machine translation can handle 90% of standard municipal documents with acceptable quality.", observations: "Quality acceptable for 8 of 10 target languages. Arabic and Somali need human review.", completed: true, result: "Translation quality rated 4.1/5 by bilingual reviewers for 8 languages.", divergence: "Arabic and Somali translations required 40% manual correction.", recommendation: "iterate", apis_used: ["API-014"], system_impact: "Minimal — standalone service.", classification: "efficiency", visibility: "internal", org_id: "org-eskilstuna", fast_track: true, sandbox_start_date: "2025-12-20", sandbox_weeks: 10, approval_status: "approved", approver: "Elena Vasquez", exit_log_approved: true, outcome_routing: "iterate" },
      { id: "exp-ft-4", title: "Predictive School Absence Model", owner: "Lena Berggren", department: "Education & Schools", started_weeks_ago: 16, timebox_weeks: 12, progress_percent: 100, tags: ["#ml", "#education", "#fast-track"], isolated: true, no_production_access: true, mock_data_only: true, hypothesis: "ML model can predict student absences 3 days ahead with 75% accuracy.", observations: "Model achieved 68% accuracy. Insufficient for actionable intervention.", completed: true, result: "Accuracy below threshold. Model relies too heavily on seasonal patterns.", divergence: "Privacy concerns raised about using individual student data.", recommendation: "stop", apis_used: ["API-007"], system_impact: "None — experiment stopped before integration.", classification: "innovation", visibility: "internal", org_id: "org-eskilstuna", fast_track: true, sandbox_start_date: "2025-11-15", sandbox_weeks: 12, approval_status: "approved", approver: "Lena Berggren", exit_log_approved: true, outcome_routing: "stop" },
    ]);

    await upsert("knowledge_published_tools", [
      { id: "tool-1", name: "Building Permit Portal", department: "Urban Planning & Environment", description: "Digital self-service for submitting and tracking building permit applications.", status: "Active", apis: ["Castor", "BankID", "Eskilstuna Open Data"], classification: "transformation", visibility: "public", org_id: "org-eskilstuna", municipality_name: "Eskilstuna Municipality", contact_email: "elena@eskilstuna.demo", linked_experiment_id: "exp-2" },
      { id: "tool-2", name: "Meeting Assistant", department: "IT & Digitalisation", description: "Automatic transcription and summarisation of internal meetings.", status: "Active (Beta)", apis: ["Azure Speech", "Microsoft Graph"], classification: "efficiency", visibility: "internal", org_id: "org-eskilstuna", municipality_name: "Eskilstuna Municipality", contact_email: "anna.lindstrom@eskilstuna.se" },
      { id: "tool-3", name: "Home Care Scheduler", department: "Social Services", description: "Optimised scheduling based on care recipient needs and available staff.", status: "Archived", apis: ["Pulsen Combine"], classification: "efficiency", visibility: "internal", org_id: "org-eskilstuna", municipality_name: "Linköping Municipality", contact_email: "digital@linkoping.se" },
      { id: "tool-4", name: "Citizen Chatbot (Fråga Kommunen)", department: "IT & Digitalisation", description: "NLP-powered chatbot handling 60% of initial citizen enquiries. Routes complex cases to caseworkers.", status: "Active", apis: ["Rasa NLU", "BankID"], classification: "innovation", visibility: "public", org_id: "org-eskilstuna", municipality_name: "Helsingborg Municipality", contact_email: "digital@helsingborg.se" },
      { id: "tool-5", name: "Open Data Portal Generator", department: "IT & Digitalisation", description: "Automated publishing pipeline for open data sets. Converts internal databases to DCAT-compliant public feeds.", status: "Active", apis: ["CKAN", "Open Budget Data API"], classification: "transformation", visibility: "public", org_id: "org-eskilstuna", municipality_name: "Göteborg Municipality", contact_email: "opendata@goteborg.se" },
      { id: "tool-6", name: "Digital Signature Service", department: "Municipal Executive Office", description: "Enables digital signing of municipal contracts and decisions using BankID and qualified e-signatures.", status: "Active", apis: ["BankID", "DIGG Digital Mail"], classification: "efficiency", visibility: "partner", org_id: "org-eskilstuna", municipality_name: "Sundsvall Municipality", contact_email: "digital@sundsvall.se" },
    ]);

    // 11. Seed KPI values
    await upsert("kpi_values", [
      { kpi_id: "capacity", label: "Capacity Readiness", value: "78%", trend: "up", trend_label: "↑ 3% vs Q4", last_updated: "2026-03-10", source: "System inventory", helper: "Share of systems within acceptable utilization thresholds", link_to: "/system-map", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "accessibility", label: "Digital Accessibility", value: "85%", trend: "up", trend_label: "↑ 5% YoY", last_updated: "2026-03-01", source: "WCAG audit", helper: "Services meeting WCAG 2.1 AA or above", link_to: "/system-map", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "security", label: "Security Posture", value: "72%", trend: "down", trend_label: "↓ 2% — 3 new CVEs", last_updated: "2026-03-12", source: "Risk register", helper: "Composite score: patched systems, reviewed configs, MFA coverage", link_to: "/risk", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "resolution", label: "IT Problem Resolution", value: "4.2h", trend: "down", trend_label: "↓ 0.8h vs Feb", last_updated: "2026-03-14", source: "Operations feed", helper: "Mean time to resolve P1/P2 incidents", link_to: "/system-map", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "risks", label: "Critical Risks Open", value: "3", trend: "stable", trend_label: "Same as last week", last_updated: "2026-03-14", source: "Risk register", helper: "Risks with impact × likelihood ≥ 16", link_to: "/risk", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "api-reuse", label: "APIs Reused Across Municipalities", value: "7", trend: "up", trend_label: "+2 this quarter", last_updated: "2026-03-01", source: "API catalog", helper: "APIs consumed by 2+ municipalities via partner/public channels", link_to: "/api", role: "cto", org_id: "org-eskilstuna" },
      { kpi_id: "budget-ratio", label: "Budgeting Ratio", value: "96.2%", trend: "up", trend_label: "↑ 1.1% vs Q4", last_updated: "2026-03-01", source: "Finance upload", helper: "Actual spend vs. approved budget", link_to: "/cost", role: "cfo", org_id: "org-eskilstuna" },
      { kpi_id: "solvency", label: "Near-Term Solvency", value: "1.42", trend: "stable", trend_label: "Stable YoY", last_updated: "2026-03-01", source: "Finance upload", helper: "Current assets / current liabilities", link_to: "/cost", role: "cfo", org_id: "org-eskilstuna" },
      { kpi_id: "roi", label: "Taxpayer ROI", value: "7.3/10", trend: "up", trend_label: "↑ 0.4 vs 2025", last_updated: "2026-02-15", source: "Citizen survey", helper: "Resident satisfaction with digital services", link_to: "/cost", role: "cfo", org_id: "org-eskilstuna" },
      { kpi_id: "legacy-cost", label: "Cost of Legacy Systems", value: "68.5 MSEK", trend: "down", trend_label: "↓ 3.2 MSEK YoY", last_updated: "2026-03-01", source: "System inventory", helper: "Annual spend on legacy or end-of-life systems", link_to: "/cost", role: "cfo", org_id: "org-eskilstuna" },
      { kpi_id: "shared-potential", label: "Shared Solution Potential", value: "24.3 MSEK", trend: "up", trend_label: "↑ 6 MSEK identified", last_updated: "2026-02-15", source: "API catalog comparison", helper: "Estimated savings if duplicated systems/APIs were shared", link_to: "/api", role: "cfo", org_id: "org-eskilstuna" },
      { kpi_id: "diversity", label: "Workforce Diversity", value: "47%", trend: "up", trend_label: "↑ 2% vs 2025", last_updated: "2026-02-01", source: "HR data", helper: "Share of underrepresented groups in leadership", link_to: "/governance", role: "coo", org_id: "org-eskilstuna" },
      { kpi_id: "satisfaction", label: "Resident Satisfaction", value: "7.3/10", trend: "up", trend_label: "↑ 0.4 vs 2025", last_updated: "2026-02-15", source: "Citizen survey", helper: "Overall satisfaction with municipal digital services", link_to: "/knowledge", role: "coo", org_id: "org-eskilstuna" },
      { kpi_id: "participation", label: "Public Participation", value: "12,400", trend: "up", trend_label: "↑ 18% vs Q4", last_updated: "2026-03-01", source: "E-services platform", helper: "Citizen interactions through digital participation channels", link_to: "/knowledge", role: "coo", org_id: "org-eskilstuna" },
      { kpi_id: "processing", label: "Request Processing Time", value: "3.2 days", trend: "down", trend_label: "↓ 0.8 days vs Q4", last_updated: "2026-03-10", source: "Operations feed", helper: "Average time to process citizen requests", link_to: "/system-map", role: "coo", org_id: "org-eskilstuna" },
      { kpi_id: "public-services", label: "Digital Services Available", value: "42", trend: "up", trend_label: "↑ 5 new this year", last_updated: "2026-03-01", source: "E-services platform", helper: "Number of fully digital citizen services", link_to: "/public", role: "public", org_id: "org-eskilstuna" },
      { kpi_id: "public-satisfaction", label: "Service Satisfaction", value: "4.2/5", trend: "up", trend_label: "↑ 0.3 vs 2025", last_updated: "2026-02-15", source: "Citizen survey", helper: "Average citizen rating of digital services", link_to: "/public", role: "public", org_id: "org-eskilstuna" },
    ], "kpi_id,role,org_id");

    // 12. Seed contracts
    await upsert("contracts", [
      { id: "CTR-001", vendor_id: "VND-005", system_id: "SYS-001", title: "E-Services Portal License & Support", annual_cost: 4200, start_date: "2022-07-01", end_date: "2026-06-30", lock_in_risk: "medium", renewal_type: "manual", org_id: "org-eskilstuna" },
      { id: "CTR-002", vendor_id: "VND-001", system_id: "SYS-002", title: "Microsoft Enterprise Agreement", annual_cost: 6200, start_date: "2024-01-01", end_date: "2028-12-31", lock_in_risk: "high", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-003", vendor_id: "VND-002", system_id: "SYS-003", title: "CGI Procapita License", annual_cost: 3100, start_date: "2023-04-01", end_date: "2027-03-31", lock_in_risk: "high", renewal_type: "manual", org_id: "org-eskilstuna" },
      { id: "CTR-004", vendor_id: "VND-003", system_id: "SYS-004", title: "Visma HR+ Support Agreement", annual_cost: 2400, start_date: "2021-01-01", end_date: "2026-12-31", lock_in_risk: "high", renewal_type: "manual", org_id: "org-eskilstuna" },
      { id: "CTR-005", vendor_id: "VND-004", system_id: "SYS-007", title: "Dell/Cisco Data Center Hardware", annual_cost: 5200, start_date: "2024-01-01", end_date: "2029-12-31", lock_in_risk: "medium", renewal_type: "manual", org_id: "org-eskilstuna" },
      { id: "CTR-006", vendor_id: "VND-006", system_id: "SYS-008", title: "Esri GIS License", annual_cost: 1200, start_date: "2023-07-01", end_date: "2027-06-30", lock_in_risk: "medium", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-007", vendor_id: "VND-007", system_id: "SYS-009", title: "IST School Platform SaaS", annual_cost: 1500, start_date: "2024-01-01", end_date: "2027-12-31", lock_in_risk: "medium", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-008", vendor_id: "VND-009", system_id: "SYS-006", title: "Dell EMC Storage Support", annual_cost: 800, start_date: "2022-10-01", end_date: "2026-09-30", lock_in_risk: "low", renewal_type: "manual", org_id: "org-eskilstuna" },
      { id: "CTR-009", vendor_id: "VND-008", system_id: "SYS-010", title: "Tekis ByggR Annual License", annual_cost: 900, start_date: "2023-10-01", end_date: "2027-09-30", lock_in_risk: "low", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-010", vendor_id: "VND-001", system_id: "SYS-011", title: "Microsoft 365 E5 Subscription", annual_cost: 2200, start_date: "2024-01-01", end_date: "2028-12-31", lock_in_risk: "high", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-011", vendor_id: "VND-001", system_id: "SYS-012", title: "SharePoint Online License", annual_cost: 600, start_date: "2024-01-01", end_date: "2028-12-31", lock_in_risk: "medium", renewal_type: "auto", org_id: "org-eskilstuna" },
      { id: "CTR-012", vendor_id: "VND-010", system_id: null, title: "Formpipe Platina — Document Management", annual_cost: 480, start_date: "2022-01-01", end_date: "2026-12-31", lock_in_risk: "medium", renewal_type: "manual", org_id: "org-eskilstuna" },
    ]);

    // 13. Seed opportunity cost items
    await upsert("opportunity_cost_items", [
      { id: "OPC-001", function_name: "BankID Identity Verification", linked_api_id: "API-005", linked_system_id: "SYS-001", your_cost: 320, peer_average_cost: 210, peer_count: 14, adopted: false, org_id: "org-eskilstuna", peer_details: [
        { municipality_alias: "Stockholm", cost: 180 }, { municipality_alias: "Göteborg", cost: 195 }, { municipality_alias: "Malmö", cost: 220 }, { municipality_alias: "Uppsala", cost: 200 }, { municipality_alias: "Linköping", cost: 190 }, { municipality_alias: "Västerås", cost: 230 }, { municipality_alias: "Örebro", cost: 215 }, { municipality_alias: "Helsingborg", cost: 240 }, { municipality_alias: "Norrköping", cost: 205 }, { municipality_alias: "Jönköping", cost: 210 }, { municipality_alias: "Umeå", cost: 225 }, { municipality_alias: "Lund", cost: 195 }, { municipality_alias: "Sundsvall", cost: 218 }, { municipality_alias: "Borås", cost: 217 },
      ] },
      { id: "OPC-002", function_name: "GIS Map Hosting", linked_api_id: "API-006", linked_system_id: "SYS-008", your_cost: 180, peer_average_cost: 120, peer_count: 9, adopted: true, org_id: "org-eskilstuna", peer_details: [
        { municipality_alias: "Stockholm", cost: 110 }, { municipality_alias: "Göteborg", cost: 125 }, { municipality_alias: "Malmö", cost: 130 }, { municipality_alias: "Uppsala", cost: 105 }, { municipality_alias: "Linköping", cost: 118 }, { municipality_alias: "Västerås", cost: 135 }, { municipality_alias: "Örebro", cost: 112 }, { municipality_alias: "Helsingborg", cost: 120 }, { municipality_alias: "Norrköping", cost: 125 },
      ] },
      { id: "OPC-003", function_name: "School Data Integration", linked_api_id: "API-007", linked_system_id: "SYS-009", your_cost: 260, peer_average_cost: 180, peer_count: 11, adopted: false, org_id: "org-eskilstuna", peer_details: [
        { municipality_alias: "Stockholm", cost: 165 }, { municipality_alias: "Göteborg", cost: 190 }, { municipality_alias: "Malmö", cost: 175 }, { municipality_alias: "Uppsala", cost: 185 }, { municipality_alias: "Linköping", cost: 170 }, { municipality_alias: "Västerås", cost: 195 }, { municipality_alias: "Örebro", cost: 180 }, { municipality_alias: "Helsingborg", cost: 188 }, { municipality_alias: "Norrköping", cost: 172 }, { municipality_alias: "Jönköping", cost: 178 }, { municipality_alias: "Umeå", cost: 182 },
      ] },
      { id: "OPC-004", function_name: "E-Service Chatbot NLP", linked_api_id: "API-014", linked_system_id: "SYS-001", your_cost: 150, peer_average_cost: 95, peer_count: 7, adopted: false, org_id: "org-eskilstuna", peer_details: [
        { municipality_alias: "Stockholm", cost: 85 }, { municipality_alias: "Göteborg", cost: 90 }, { municipality_alias: "Malmö", cost: 105 }, { municipality_alias: "Uppsala", cost: 92 }, { municipality_alias: "Linköping", cost: 88 }, { municipality_alias: "Västerås", cost: 100 }, { municipality_alias: "Örebro", cost: 105 },
      ] },
      { id: "OPC-005", function_name: "Document Management", linked_api_id: "API-011", linked_system_id: "SYS-006", your_cost: 200, peer_average_cost: 160, peer_count: 6, adopted: false, org_id: "org-eskilstuna", peer_details: [
        { municipality_alias: "Stockholm", cost: 145 }, { municipality_alias: "Göteborg", cost: 155 }, { municipality_alias: "Malmö", cost: 170 }, { municipality_alias: "Uppsala", cost: 162 }, { municipality_alias: "Linköping", cost: 158 }, { municipality_alias: "Västerås", cost: 170 },
      ] },
    ]);

    // 14. Set linked_risk_ids on some risks
    const { error: linkErr1 } = await supabase.from("risks").update({ linked_risk_ids: "RSK-002,RSK-011" }).eq("id", "RSK-001");
    if (linkErr1) errors.push(`link RSK-001: ${linkErr1.message}`);
    const { error: linkErr2 } = await supabase.from("risks").update({ linked_risk_ids: "RSK-001,RSK-004" }).eq("id", "RSK-002");
    if (linkErr2) errors.push(`link RSK-002: ${linkErr2.message}`);
    const { error: linkErr3 } = await supabase.from("risks").update({ linked_risk_ids: "RSK-009,RSK-003" }).eq("id", "RSK-012");
    if (linkErr3) errors.push(`link RSK-012: ${linkErr3.message}`);

    // 15. Set risk_appetite_threshold on org
    const { error: threshErr } = await supabase.from("organizations").update({ risk_appetite_threshold: 16 }).eq("id", "org-eskilstuna");
    if (threshErr) errors.push(`threshold: ${threshErr.message}`);

    // 16. Seed risk_score_history — 6 weekly snapshots per risk
    const risks = [
      { id: "RSK-001", l: 5, i: 5 }, { id: "RSK-002", l: 4, i: 5 }, { id: "RSK-003", l: 4, i: 4 },
      { id: "RSK-004", l: 3, i: 4 }, { id: "RSK-005", l: 3, i: 3 }, { id: "RSK-006", l: 2, i: 3 },
      { id: "RSK-007", l: 3, i: 2 }, { id: "RSK-008", l: 2, i: 2 }, { id: "RSK-009", l: 2, i: 5 },
      { id: "RSK-010", l: 3, i: 5 }, { id: "RSK-011", l: 3, i: 4 }, { id: "RSK-012", l: 2, i: 5 },
    ];
    // Clear old history first
    await supabase.from("risk_score_history").delete().neq("id", "00000000-0000-0000-0000-000000000000");
    const historyRows: any[] = [];
    const todayDate = new Date();
    for (const r of risks) {
      const baseScore = r.l * r.i;
      for (let w = 5; w >= 0; w--) {
        const d = new Date(todayDate);
        d.setDate(d.getDate() - w * 7);
        const variation = Math.floor(Math.random() * 5) - 2; // -2 to +2
        const score = Math.max(1, Math.min(25, baseScore + variation));
        historyRows.push({ risk_id: r.id, org_id: "org-eskilstuna", score, recorded_at: d.toISOString().split("T")[0] });
      }
    }
    const { error: histErr } = await supabase.from("risk_score_history").insert(historyRows);
    if (histErr) errors.push(`risk_score_history: ${histErr.message}`);
    else errors.push(`risk_score_history: OK inserted=${historyRows.length}`);

    // ── Citizen Impact Score History ──────────────────────────────────────
    await supabase.from("citizen_impact_history").delete().neq("id", "00000000-0000-0000-0000-000000000000");
    const cisRows: any[] = [];
    const cisBase = { accessibility: 52, time_savings: 48, engagement: 55, trust: 50, equity: 60 };
    for (let m = 5; m >= 0; m--) {
      const d = new Date(todayDate);
      d.setMonth(d.getMonth() - m);
      const progress = (5 - m) * 3.5; // gradual increase
      const acc = Math.min(100, Math.round(cisBase.accessibility + progress + Math.random() * 4 - 2));
      const ts = Math.min(100, Math.round(cisBase.time_savings + progress * 1.1 + Math.random() * 4 - 2));
      const eng = Math.min(100, Math.round(cisBase.engagement + progress * 0.8 + Math.random() * 4 - 2));
      const tru = Math.min(100, Math.round(cisBase.trust + progress * 0.9 + Math.random() * 4 - 2));
      const eq = Math.min(100, Math.round(cisBase.equity + progress * 0.7 + Math.random() * 4 - 2));
      const score = Math.round(0.20 * acc + 0.25 * ts + 0.20 * eng + 0.20 * tru + 0.15 * eq);
      cisRows.push({
        org_id: "org-eskilstuna", score, accessibility: acc, time_savings: ts,
        engagement: eng, trust: tru, equity: eq,
        recorded_month: d.toISOString().split("T")[0],
      });
    }
    const { error: cisErr } = await supabase.from("citizen_impact_history").insert(cisRows);
    if (cisErr) errors.push(`citizen_impact_history: ${cisErr.message}`);
    else errors.push(`citizen_impact_history: OK inserted=${cisRows.length}`);

    return new Response(JSON.stringify({ success: errors.every(e => e.includes("OK")), details: errors }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: unknown) {
    return new Response(JSON.stringify({ error: (error as Error).message, partial_errors: errors }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
